import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    APPWRITE_CHAEA_PROJECT_ID = os.getenv('APPWRITE_CHAEA_PROJECT_ID')
    APPWRITE_CHAEA_API_KEY = os.getenv('APPWRITE_CHAEA_API_KEY')
    APPWRITE_ENDPOINT = os.getenv('APPWRITE_ENDPOINT')
    APPWRITE_CHAEA_DATABASE_ID = os.getenv('APPWRITE_CHAEA_DATABASE_ID')
    APPWRITE_CHAEA_PROFILES_COLLECTION_ID = os.getenv('APPWRITE_CHAEA_PROFILES_COLLECTION_ID')
    APPWRITE_CHAEA_RESPONSES_COLLECTION_ID = os.getenv('APPWRITE_CHAEA_RESPONSES_COLLECTION_ID')
    APPWRITE_ADAPTIVE_EVALUATIONS_COLLECTION_ID = os.getenv('APPWRITE_ADAPTIVE_EVALUATIONS_COLLECTION_ID')
    APPWRITE_USER_CONSENTS_COLLECTION_ID = os.getenv('APPWRITE_USER_CONSENTS_COLLECTION_ID')